=== HeapStone/project-common-uti/base-servlet/WebRoot/WEB-INF/dtd/BaseDao-config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
 	@author: wanglei
    @version 1.0
-->
       <!ELEMENT namespace (resultMap,sql*)>
       <!ELEMENT resultMap (id,result*)>
       <!ELEMENT result (#PCDATA)>
       <!ELEMENT id (generator)>
       <!ELEMENT generator (#PCDATA)>
       <!ELEMENT sql (#PCDATA)>
		<!ATTLIST sql type CDATA #REQUIRED>
		<!ATTLIST sql id CDATA #IMPLIED>
		<!ATTLIST generator class (uuid|sequence) "uuid">
	    <!ATTLIST namespace
	     name CDATA #REQUIRED
	     class CDATA #REQUIRED
	     table CDATA #REQUIRED
	    >
       <!ATTLIST result
         column CDATA  #REQUIRED
         property CDATA	#REQUIRED
        >
        <!ATTLIST id
         column CDATA  #REQUIRED
         property CDATA	#REQUIRED
        >

=== HeapStone/project-common-uti/baseservlet/build/classes/com/demo/model/User-BaseDao-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE baseservlet-config SYSTEM "/WEB-INF/dtd/BaseDao-config.dtd">
<namespace name="" class="" table="">
<resultMap>
    <id column="id" property="id">
      <generator class="uuid"/>
    </id>
    <result column="userName" property="userName" />
    <result column="userAge" property="userAge" />
    <result column="userAddress" property="userAddress" />
</resultMap>
<sql id="" type="">
<![CDATA[ ]]>
</sql>
</namespace>
